export enum ENV {
  APP_PORT = 'APP_PORT',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  DATABASE_URL = 'DATABASE_URL',
  TELEGRAM_TOKEN = 'TELEGRAM_TOKEN',
  COOKIE_SECRET = 'COOKIE_SECRET',
  JWT_SECRET = 'JWT_SECRET',
}
